Title: 355211 – net-zope/zope-interface-3.6.1 fails to build
URL: https://bugs.gentoo.org/show_bug.cgi?id=355211

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 355211
net-zope/zope-interface-3.6.1 fails to build
Last modified: 2011-02-18 14:34:06 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 355211 
      - net-zope/zope-interface-3.6.1 fails to build


Summary:
net-zope/zope-interface-3.6.1 fails to build
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

x86
        Linux
      







Importance:
      
High
       normal
      


Assignee:

net-zope (OBSOLETE)








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2011-02-16 17:10 UTC by Justin Capella





      Modified:
    
2011-02-18 14:34 UTC
      (History)
    




          CC List:
        

1 
          user
          
            (show)
          



python









See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Justin Capella





          2011-02-16 17:10:24 UTC
        

=net-zope/zope-interface-3.6.1


Traceback (most recent call last):
  File "setup.py", line 131, in <module>
    **extra)
  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 222, in __init__
    for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 455, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2253, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2039, in parse_map
    raise ValueError("Entry points must be listed in groups")
ValueError: Entry points must be listed in groups
 * ERROR: net-zope/zope-interface-3.6.1 failed (compile phase):
 *   Building failed with CPython 2.7 in distutils_building() function




Comment 1


Justin Capella





          2011-02-16 17:12:10 UTC
        

Portage 2.1.9.40 (default/linux/x86/10.0, gcc-4.5.2, glibc-2.13-r1, 2.6.36-gentoo-r5 i686)
=================================================================
System uname: Linux-2.6.36-gentoo-r5-i686-Genuine_Intel-R-_CPU_T1300_@_1.66GHz-with-gentoo-2.0.1
Timestamp of tree: Wed, 16 Feb 2011 16:30:01 +0000
app-shells/bash:     4.1_p9
dev-java/java-config: 2.1.11-r3
dev-lang/python:     2.7.1, 3.1.3
dev-util/cmake:      2.8.3-r1
sys-apps/baselayout: 2.0.1-r1
sys-apps/openrc:     0.7.0
sys-apps/sandbox:    2.5
sys-devel/autoconf:  2.13, 2.68
sys-devel/automake:  1.10.3, 1.11.1
sys-devel/binutils:  2.21
sys-devel/gcc:       4.5.2
sys-devel/gcc-config: 1.4.1
sys-devel/libtool:   2.4-r1
sys-devel/make:      3.82
virtual/os-headers:  2.6.36.1 (sys-kernel/linux-headers)
ACCEPT_KEYWORDS="x86 ~x86"
ACCEPT_LICENSE="*"
CBUILD="i686-pc-linux-gnu"
CFLAGS="-O2 -march=prescott -pipe -fomit-frame-pointer"
CHOST="i686-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/env.d/java/ /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -march=prescott -pipe -fomit-frame-pointer"
DISTDIR="/usr/portage/distfiles"
FEATURES="assume-digests binpkg-logs distlocks fixlafiles fixpackages news parallel-fetch protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch"
FFLAGS=""
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="C"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --compress --force --whole-file --delete --stats --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
PORTDIR="/usr/portage"
PORTDIR_OVERLAY="/usr/local/portage"
SYNC="rsync://rsync.gentoo.org/gentoo-portage"
USE="X aac alsa avahi bash-completion bluetooth bzip2 cairo caps cdda cracklib crypt cscope cxx dbus dev dga dvd encode fat ffmpeg flac fontconfig gdbm gif gnome gnome-keyring gnutls gphoto2 gpm gstreamer gtk hal iconv ieee1394 ipod ipv6 jack jpeg jpeg2k lame libnotify lzma lzo mad mmx mono mp3 mpeg nautilus ncurses networkmanager nls nptl opengl pam pcre perl png python readline samba sdl sqlite sse sse2 ssl svg system-sqlite taglib threads truetype udev unicode upnp usb vim-syntax vorbis x264 x86 xcb xml xulrunner xv xvid zlib" ALSA_PCM_PLUGINS="*" ELIBC="glibc" INPUT_DEVICES="evdev keyboard mouse synaptics vmmouse" KERNEL="linux" USERLAND="GNU" VIDEO_CARDS="intel vmware" 
Unset:  CPPFLAGS, CTARGET, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, LINGUAS, MAKEOPTS, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS





Comment 2


Arfrever Frehtes Taifersar Arahesis (RETIRED)






          2011-02-16 17:16:16 UTC
        

One of your entry_points.txt files is broken.




Comment 3


Justin Capella





          2011-02-16 21:26:19 UTC
        

(In reply to comment #2)
> One of your entry_points.txt files is broken.
> 

I did something along the lines of find /usr/lib/ -name entry_points.txt | xargs less

and suspect that the following is responsible, its content was the most different:

dev-python/flup-1.0.2 (/usr/lib/python2.6/site-packages/flup-1.0.2-py2.6.egg-info/entry_points.txt)


    [paste.server_runner]
    ajp = flup.server.paste_factory:run_ajp_thread
    fcgi = flup.server.paste_factory:run_fcgi_thread
    scgi = flup.server.paste_factory:run_scgi_thread
    ajp_thread = flup.server.paste_factory:run_ajp_thread
    fcgi_thread = flup.server.paste_factory:run_fcgi_thread
    scgi_thread = flup.server.paste_factory:run_scgi_thread
    ajp_fork = flup.server.paste_factory:run_ajp_fork
    fcgi_fork = flup.server.paste_factory:run_fcgi_fork
    scgi_fork = flup.server.paste_factory:run_scgi_fork

I do not know why this package was installed, it didn't seem to be needed by any depends. Removing it solved the problem. Thank you!

(Fix: emerge -c dev-python/flip)




Comment 4


Arfrever Frehtes Taifersar Arahesis (RETIRED)






          2011-02-16 23:56:12 UTC
        

It's strange, because I have dev-python/flup-1.0.2 installed...




Comment 5


Arfrever Frehtes Taifersar Arahesis (RETIRED)






          2011-02-18 14:34:06 UTC
        

(In reply to comment #3)
> Removing it solved the problem.

I'm closing this bug.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

