Title: 119975 – pygtk-2.8.2.ebuild: Digest verification Failed.
URL: https://bugs.gentoo.org/show_bug.cgi?id=119975

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 119975
pygtk-2.8.2.ebuild: Digest verification Failed.
Last modified: 2006-01-22 13:54:22 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 119975 
      - pygtk-2.8.2.ebuild: Digest verification Failed.


Summary:
pygtk-2.8.2.ebuild: Digest verification Failed.
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

New packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Gentoo Linux bug wranglers








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2006-01-22 13:10 UTC by Ruben Jenster





      Modified:
    
2006-01-22 13:54 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Ruben Jenster





          2006-01-22 13:10:48 UTC
        

Have synced several times.

Calculating dependencies ...done!
>>> emerge (1 of 18) dev-python/pygtk-2.8.2 to /
>>> md5 files   ;-) pygtk-2.6.0.ebuild
>>> md5 files   ;-) pygtk-2.2.0.ebuild
>>> md5 files   ;-) pygtk-2.4.1.ebuild
>>> md5 files   ;-) pygtk-2.6.2.ebuild
>>> md5 files   ;-) pygtk-2.8.0-r1.ebuild
>>> md5 files   ;-) pygtk-2.0.0-r1.ebuild
>>> md5 files   ;-) pygtk-1.99.13-r1.ebuild
>>> md5 files   ;-) pygtk-0.6.11.ebuild
>>> md5 files   ;-) pygtk-2.0.0.ebuild
>>> md5 files   ;-) pygtk-2.6.1.ebuild
>>> md5 files   ;-) pygtk-0.6.11-r1.ebuild

!!! Digest verification Failed:
!!!    /usr/portage/dev-python/pygtk/pygtk-2.8.2.ebuild
!!! Reason: Filesize does not match recorded size

>>> Please ensure you have sync'd properly. Please try 'emerge sync' and
>>> optionally examine the file(s) for corruption. A sync will fix most cases.




Comment 1


Jakub Moc (RETIRED)






          2006-01-22 13:13:47 UTC
        

Works fine here, please emerge sync again.




Comment 2


Björn Ruberg





          2006-01-22 13:54:22 UTC
        

Perhaps your download is corrupt.
Delete /usr/portage/distfiles/pygtk-2.8.2.tar.bz2 and try again.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

