Title: 623180 – app-crypt/certbot-0.14.1 segmentation fault
URL: https://bugs.gentoo.org/show_bug.cgi?id=623180

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 623180
app-crypt/certbot-0.14.1 segmentation fault
Last modified: 2017-07-02 08:17:09 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 623180 
      - app-crypt/certbot-0.14.1 segmentation fault


Summary:
app-crypt/certbot-0.14.1 segmentation fault
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
Normal
       normal
      


Assignee:

Manuel Rüger (RETIRED)








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2017-06-30 18:31 UTC by François Valenduc





      Modified:
    
2017-07-02 08:17 UTC
      (History)
    




          CC List:
        

1 
          user
          
            (show)
          



jstein









See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


François Valenduc





          2017-06-30 18:31:07 UTC
        

Each time I run certbot renew, I get the following segemntation fault:

certbot[4794]: segfault at 7fcd14c27810 ip 00007fcd14c27810 sp 00007ffe4f470fb8 error 15 in _openssl.abi3.so[7fcd14c1e000+a000]

I am using certbot-apache-0.14.1




Comment 1


François Valenduc





          2017-07-02 08:17:09 UTC
        

Recompiling dev_python/cryptography solved the problem.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

