Title: 317103 – dev-util/eric-4.4.2 fails to install
URL: https://bugs.gentoo.org/show_bug.cgi?id=317103

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 317103
dev-util/eric-4.4.2 fails to install
Last modified: 2010-04-26 11:52:28 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 317103 
      - dev-util/eric-4.4.2 fails to install


Summary:
dev-util/eric-4.4.2 fails to install
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

x86
        Linux
      







Importance:
      
High
       major
      


Assignee:

Gentoo Linux bug wranglers








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2010-04-25 11:21 UTC by 5p4md00d





      Modified:
    
2010-04-26 11:52 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


5p4md00d





          2010-04-25 11:21:56 UTC
        

Installation of dev-util/eric fails. Here's the log:
 * CPV:  dev-util/eric-4.4.2                                                  
 * REPO: gentoo                                                               
 * USE:  elibc_glibc kde kernel_linux spell userland_GNU x86                  
 * Applying eric-4.4-no-interactive.patch ...                             [ ok ]
 * Applying remove_coverage.patch ...                                     [ ok ]
 * Installation of dev-util/eric-4.4.2 with CPython 2.6...                      
Checking dependencies                                                           
Python Version: 2.6.4                                                           
Found PyQt                                                                      
Found QScintilla2                                                               
Qt Version: 4.6.2                                                               
PyQt Version:  4.7.0                                                            
QScintilla Version:  2.4                                                        
All dependencies ok.                                                            

Compiling user interface files...
An internal error occured.  Please report all the output of the program,
including the following traceback, to eric4-bugs@eric-ide.python-projects.org.

Traceback (most recent call last):
  File "install.py", line 790, in <module>
    main(sys.argv)                        
  File "install.py", line 729, in main    
    compileUiFiles()                      
  File "install.py", line 647, in compileUiFiles
    compileUiDir("eric", True, pyName)          
  File "/usr/lib/python2.6/site-packages/PyQt4/uic/__init__.py", line 94, in compileUiDir
    compile_ui(root, ui)                                                                 
  File "/usr/lib/python2.6/site-packages/PyQt4/uic/__init__.py", line 86, in compile_ui  
    compileUi(ui_file, py_file, **compileUi_args)                                        
  File "/usr/lib/python2.6/site-packages/PyQt4/uic/__init__.py", line 128, in compileUi  
    winfo = compiler.UICompiler().compileUi(uifile, pyfile)                              
  File "/usr/lib/python2.6/site-packages/PyQt4/uic/Compiler/compiler.py", line 14, in __init__
    CompilerCreatorPolicy())                                                                  
  File "/usr/lib/python2.6/site-packages/PyQt4/uic/uiparser.py", line 87, in __init__         
    self.factory = QObjectCreator(creatorPolicy)                                              
  File "/usr/lib/python2.6/site-packages/PyQt4/uic/objcreator.py", line 57, in __init__       
    self._cwFilters.append(plugin_locals["getFilter"]())                                      
  File "<string>", line 22, in getFilter                                                      
RuntimeError: the sip module implements API v7.0 but the PyKDE4.kdeui module requires API v6.0
 * ERROR: dev-util/eric-4.4.2 failed:                                                         
 *   Installation failed with CPython 2.6 in installation() function                          
 *                                                                                            
 * Call stack:                                                                                
 *     ebuild.sh, line   54:  Called src_install                                              
 *   environment, line 4097:  Called python_execute_function 'installation'                   
 *   environment, line 2968:  Called die                                                      
 * The specific snippet of code:                                                              
 *                       die "${failure_message}";                                            
 *                                                                                            
 * If you need support, post the output of 'emerge --info =dev-util/eric-4.4.2',              
 * the complete build log and the output of 'emerge -pqv =dev-util/eric-4.4.2'.               
 * The complete build log is located at '/var/log/portage/dev-util:eric-4.4.2:20100425-094052.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-util/eric-4.4.2/temp/environment'.
 * S: '/var/tmp/portage/dev-util/eric-4.4.2/work/eric4-4.4.2'

If you need more information, like `emerge --info`, just ask.




Comment 1


Rafał Mużyło





          2010-04-25 20:19:48 UTC
        

The error suggests that you didn't rebuild enough
after sip/PyQt4 update.




Comment 2


5p4md00d





          2010-04-26 11:52:28 UTC
        

(In reply to comment #1)
> The error suggests that you didn't rebuild enough
> after sip/PyQt4 update.
> 

You are correct -- rebuilding x11-libs/qscintilla and kde-base/pykde4 solved the problem. Ah, I should run elogv more often. Anyway, thank you for your help.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

