Title: 307617 – kde-base/pykde-4.4.1 fails at install/merge stage
URL: https://bugs.gentoo.org/show_bug.cgi?id=307617

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 307617
kde-base/pykde-4.4.1 fails at install/merge stage
Last modified: 2010-03-04 00:06:54 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 307617 
      - kde-base/pykde-4.4.1 fails at install/merge stage


Summary:
kde-base/pykde-4.4.1 fails at install/merge stage
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

[OLD] KDE

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Gentoo KDE team








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2010-03-03 13:31 UTC by Matt





      Modified:
    
2010-03-04 00:06 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    




kde-base:pykde4-4.4.1:20100303-141113.log

              (kde-base:pykde4-4.4.1:20100303-141113.log,277.44 KB,
                text/plain)

            
2010-03-04 00:06 UTC,

            Matt




Details





View All

Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Matt





          2010-03-03 13:31:28 UTC
        

* Installation of kde-base/pykde4-4.4.1 with CPython 3.1...
>>> Working in BUILD_DIR: "/var/tmp/portage/kde-base/pykde4-4.4.1/work/pykde4-4.4.1-3.1_build"
make -j2 install DESTDIR=/var/tmp/portage/kde-base/pykde4-4.4.1/image/ 
make: *** No rule to make target `install'.  Stop.
 * ERROR: kde-base/pykde4-4.4.1 failed:
 *   Make install failed
 * 
 * Call stack:
 *     ebuild.sh, line   48:  Called src_install
 *   environment, line 5922:  Called python_execute_function '-s' 'do_src_install'
 *   environment, line 4694:  Called do_src_install
 *   environment, line 5919:  Called kde4-meta_src_install
 *   environment, line 3774:  Called kde4-base_src_install
 *   environment, line 3400:  Called cmake-utils_src_install
 *   environment, line 1491:  Called _execute_optionaly 'src_install'
 *   environment, line  705:  Called enable_cmake-utils_src_install
 *   environment, line 1927:  Called die
 * The specific snippet of code:
 *       emake install DESTDIR="${D}" || die "Make install failed";
 * 
 * If you need support, post the output of 'emerge --info =kde-base/pykde4-4.4.1',
 * the complete build log and the output of 'emerge -pqv =kde-base/pykde4-4.4.1'.
 * The complete build log is located at '/var/log/portage/kde-base:pykde4-4.4.1:20100303-131049.log'.
 * The ebuild environment file is located at '/var/tmp/portage/kde-base/pykde4-4.4.1/temp/environment'.
 * S: '/var/tmp/portage/kde-base/pykde4-4.4.1/work/pykde4-4.4.1'

>>> Failed to emerge kde-base/pykde4-4.4.1, Log file:




Comment 1


Matt





          2010-03-03 15:06:19 UTC
        

sorry, it's the in-portage tree pykde4 NOT from the kde-testing overlay




Comment 2


Andreas K. Hüttel







          2010-03-03 15:43:20 UTC
        


(In reply to comment #0)
>  * If you need support, post the output of 'emerge --info
> =kde-base/pykde4-4.4.1',
>  * the complete build log and the output of 'emerge -pqv
> =kde-base/pykde4-4.4.1'.
>  * The complete build log is located at
> '/var/log/portage/kde-base:pykde4-4.4.1:20100303-131049.log'.

See above... :)

And please try again with a sane (i.e. 2.x) python setting!





Comment 3


Matt





          2010-03-04 00:06:30 UTC
        

Created attachment 221985 [details]
kde-base:pykde4-4.4.1:20100303-141113.log

seems like I found the error:

Traceback (most recent call last):
  File "/usr/share/apps/cmake/modules/FindPyQt.py", line 5, in <module>
    import PyQt4.pyqtconfig
ImportError: No module named PyQt4.pyqtconfig
-- Build PyKDE4... no

-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
-----------------------------------------------------------------------------
   * Shared desktop ontologies - Desktop ontologies

-----------------------------------------------------------------------------
-- Congratulations! All external packages have been found.
-----------------------------------------------------------------------------




Comment 4


Matt





          2010-03-04 00:06:54 UTC
        

I re-installed:

qscintilla-python qscintilla PyQt4 dev-python/sip

and after that it installed fine 

oh - and btw, the system is FORCING python 3.1 ON ME ;)

eselect python list
Available Python interpreters:
  [1]   python2.5
  [2]   python2.6 *
  [3]   python3.1









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

