Title: 268578 – net-libs/gtk-vnc-0.3.8 fails to build. Falls over on pygtk-codegen error
URL: https://bugs.gentoo.org/show_bug.cgi?id=268578

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 268578
net-libs/gtk-vnc-0.3.8 fails to build. Falls over on pygtk-codegen error
Last modified: 2009-05-04 13:31:03 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 268578 
      - net-libs/gtk-vnc-0.3.8 fails to build. Falls over on pygtk-codegen error


Summary:
net-libs/gtk-vnc-0.3.8 fails to build. Falls over on pygtk-codegen error
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

[OLD] GNOME

  (show other bugs)



Hardware:

x86
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Gentoo Linux Gnome Desktop Team








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2009-05-04 11:25 UTC by James Purser





      Modified:
    
2009-05-04 13:31 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


James Purser





          2009-05-04 11:25:50 UTC
        

I am trying to install virt-manager on my system and gtk-vnc is a dependancy. Whenever I try and emerge it, I get the following:

/usr/bin/python /usr/lib/python2.6/site-packages/gtk-2.0/codegen/h2def.py vncdisplay.h > vnc.defs
/usr/bin/python: can't open file '/usr/lib/python2.6/site-packages/gtk-2.0/codegen/h2def.py': [Errno 2] No such file or directory
make[2]: *** [vnc.defs] Error 2
make[2]: Leaving directory `/var/tmp/portage/net-libs/gtk-vnc-0.3.8/work/gtk-vnc-0.3.8/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/tmp/portage/net-libs/gtk-vnc-0.3.8/work/gtk-vnc-0.3.8'
make: *** [all] Error 2
 * 
 * ERROR: net-libs/gtk-vnc-0.3.8 failed.
 * Call stack:
 *               ebuild.sh, line   49:  Called src_compile
 *             environment, line 2255:  Called base_src_compile
 *             environment, line  200:  Called base_src_work 'all'
 *             environment, line  315:  Called base_src_work 'configure' 'make'
 *             environment, line  310:  Called die
 * The specific snippet of code:
 *                       emake || die "died running emake, $FUNCNAME:make";
 *  The die message:
 *   died running emake, base_src_work:make
 * 
 * If you need support, post the topmost build error, and the call stack if relevant.
 * A complete build log is located at '/var/tmp/portage/net-libs/gtk-vnc-0.3.8/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-libs/gtk-vnc-0.3.8/temp/environment'.
 * 


Reproducible: Always

Steps to Reproduce:
1. emerge gtk-vnc
Actual Results:  
build fails with the above error

Expected Results:  
build completes

Portage 2.1.6.13 (default/linux/x86/2008.0, gcc-4.1.2, glibc-2.9_p20081201-r2, 2.6.26-gentoo-r4 i686)
=================================================================
System uname: Linux-2.6.26-gentoo-r4-i686-Genuine_Intel-R-_CPU_T2400_@_1.83GHz-with-gentoo-2.0.0
Timestamp of tree: Mon, 04 May 2009 09:30:01 +0000
distcc 3.1 i686-pc-linux-gnu [disabled]
app-shells/bash:     4.0_p17-r1
dev-java/java-config: 1.3.7-r1, 2.1.7
dev-lang/python:     2.4.4-r14, 2.5.4-r2, 2.6.2
dev-python/pycrypto: 2.0.1-r8
dev-util/cmake:      2.6.3-r1
sys-apps/baselayout: 2.0.0
sys-apps/openrc:     0.4.3-r2
sys-apps/sandbox:    1.9
sys-devel/autoconf:  2.13, 2.63-r1
sys-devel/automake:  1.5, 1.7.9-r1, 1.8.5-r3, 1.9.6-r2, 1.10.2
sys-devel/binutils:  2.19.1-r1
sys-devel/gcc-config: 1.4.1
sys-devel/libtool:   2.2.6a
virtual/os-headers:  2.6.28-r1
ACCEPT_KEYWORDS="x86 ~x86"
CBUILD="i686-pc-linux-gnu"
CFLAGS="-O2 -march=i686 -pipe"
CHOST="i686-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/kde/3.5/env /usr/kde/3.5/share/config /usr/kde/3.5/shutdown /usr/share/config /var/lib/hsqldb"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/env.d/java/ /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php5/ext-active/ /etc/php/cgi-php5/ext-active/ /etc/php/cli-php5/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/udev/rules.d"
CXXFLAGS="-O2 -march=i686 -pipe"
DISTDIR="/usr/portage/distfiles"
FEATURES="distlocks fixpackages parallel-fetch protect-owned sandbox sfperms strict unmerge-orphans userfetch"
GENTOO_MIRRORS="http://mirror.exetel.com.au/pub/gentoo/"
LANG="C"
LDFLAGS="-Wl,-O1"
LINGUAS="en_GB"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --compress --force --whole-file --delete --stats --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
PORTDIR="/usr/portage"
PORTDIR_OVERLAY="/usr/local/portage"
SYNC="rsync://rsync.gentoo.org/gentoo-portage"
USE="X a52 aac acl alsa berkdb bzip2 cli cracklib crypt cups dbus dri dvd dvdr dvdread faad2 flac fortran gdbm gif gnome gpm graphicsmagick gtk gzip hal iconv imagemagick ipv6 isdnlog java jpeg kde kvm midi mp3 mudflap mysql ncurses nls nptl nptlonly ogg opengl openmp pam pcre perl png pppd python qt3 qt4 readline reflection session spl sqlite ssl svg sysfs tcpd theora tiff unicode v4l v4l2 vorbis win32codecs x86 xorg xvid xvmc zlib" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1 emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" ALSA_PCM_PLUGINS="adpcm alaw asym copy dmix dshare dsnoop empty extplug file hooks iec958 ioplug ladspa lfloat linear meter mmap_emul mulaw multi null plug rate route share shm softvol" APACHE2_MODULES="actions alias auth_basic auth_digest authn_anon authn_dbd authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache dav dav_fs dav_lock dbd deflate dir disk_cache env expires ext_filter file_cache filter headers ident imagemap include info log_config logio mem_cache mime mime_magic negotiation proxy proxy_ajp proxy_balancer proxy_connect proxy_http rewrite setenvif so speling status unique_id userdir usertrack vhost_alias" ELIBC="glibc" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LINGUAS="en_GB" USERLAND="GNU" VIDEO_CARDS="intel"
Unset:  CPPFLAGS, CTARGET, EMERGE_DEFAULT_OPTS, FFLAGS, INSTALL_MASK, LC_ALL, MAKEOPTS, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS




Comment 1


Gilles Dartiguelongue (RETIRED)






          2009-05-04 11:42:55 UTC
        

which version of pygtk and pygobject do you have installed ? Did you run python-updater since you installed python-2.6 ?




Comment 2


James Purser





          2009-05-04 13:31:03 UTC
        

Sigh, you can close this bug. I thought I had done python-updater however it appears it wasn't successful. Upon rebuilding pygobject everything seems to be working okay.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

