Title: 347896 – python-updater can't start due to /usr/bin/python3 is not valid symlink
URL: https://bugs.gentoo.org/show_bug.cgi?id=347896

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 347896
python-updater can't start due to /usr/bin/python3 is not valid symlink
Last modified: 2010-12-10 10:56:22 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 347896 
      - python-updater can't start due to /usr/bin/python3 is not valid symlink


Summary:
python-updater can't start due to /usr/bin/python3 is not valid symlink
    








Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

[OLD] Core system

  (show other bugs)



Hardware:

x86
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Python Gentoo Team








URL:







Whiteboard:




Keywords:








Depends on:




347639



Blocks:







 

        Show dependency tree





 





      Reported:
    
2010-12-06 12:05 UTC by Lars Langhans





      Modified:
    
2010-12-10 10:56 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Lars Langhans





          2010-12-06 12:05:14 UTC
        

I try to update my machine, from a more than a year old gentoo system to a current system.

Lot of packages can't build because python3 has replaced by python3.1.

Also I can not start python-updater any more. Result is
'/usr/bin/python3' is not valid symlink

What a pitty!
# eselect python list
[1] python2.6 *
[2] python3.1

Why python-updater will take python3?
I've emerged python-updater also, but the same result.

Is there a simple way to force python-updater to use the right?

My way was to create a new /usr/bin/python3 symlink to python3.1 but I think this could be done automatically by python-updater.



Reproducible: Always




Comment 1


Arfrever Frehtes Taifersar Arahesis (RETIRED)






          2010-12-07 07:44:37 UTC
        

dev-lang/python ebuilds call 'eselect python update ...' to create appropriate symlinks. There was a short period of time, when these ebuilds weren't calling these commands. Please manually set active version of Python 3 using 'eselect python update --python3' or reinstall =dev-lang/python-3*.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

