Title: 931826 – dev-lang/python-3.13.0_beta1_p1::gentoo: test_statistics worker non-zero exit code (Exit code 1)
URL: https://bugs.gentoo.org/show_bug.cgi?id=931826

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 931826
dev-lang/python-3.13.0_beta1_p1::gentoo: test_statistics worker non-zero exit code (Exit code 1)
Last modified: 2024-09-18 20:54:55 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 931826 
      - dev-lang/python-3.13.0_beta1_p1::gentoo: test_statistics worker non-zero exit code (Exit code 1)


Summary:
dev-lang/python-3.13.0_beta1_p1::gentoo: test_statistics worker non-zero exit...
        









Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

Current packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
Normal
       normal
      


Assignee:

Python Gentoo Team








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:




931888



 

        Show dependency tree





 





      Reported:
    
2024-05-12 16:28 UTC by Conrad Kostecki





      Modified:
    
2024-09-18 20:54 UTC
      (History)
    




          CC List:
        

1 
          user
          
            (show)
          



conikost









See Also:






Package list:







Runtime testing required:

---























      Attachments
    




build.log

              (build.log,256.61 KB,
                application/octet-stream)

            
2024-05-12 16:28 UTC,

            Conrad Kostecki




Details





emerge.log

              (emerge.log,8.28 KB,
                text/plain)

            
2024-05-12 16:29 UTC,

            Conrad Kostecki




Details





build.log

              (build.log,300.41 KB,
                application/octet-stream)

            
2024-05-12 16:29 UTC,

            Conrad Kostecki




Details





Show
              Obsolete (1)
            View All

Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Conrad Kostecki






          2024-05-12 16:28:06 UTC
        

0:23:32 load avg: 1.00 [423/423] test_statistics worker non-zero exit code (Exit code 1)
Timeout (0:20:00)!
Thread 0x00007f28043a72c0 (most recent call first):
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/statistics.py", line 1747 in <lambda>
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/statistics.py", line 1724 in f_inv
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/test_statistics.py", line 2447 in test_kde_kernel_invcdfs
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/unittest/case.py", line 606 in _callTestMethod
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/unittest/case.py", line 651 in run
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/unittest/case.py", line 707 in __call__
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/unittest/suite.py", line 122 in run
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/unittest/suite.py", line 84 in __call__
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/unittest/suite.py", line 122 in run
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/unittest/suite.py", line 84 in __call__
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/testresult.py", line 146 in run
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/single.py", line 57 in _run_suite
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/single.py", line 37 in run_unittest
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/single.py", line 132 in test_func
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/single.py", line 88 in regrtest_runner
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/single.py", line 135 in _load_run_test
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/single.py", line 178 in _runtest_env_changed_exc
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/single.py", line 278 in _runtest
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/single.py", line 309 in run_single_test
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/worker.py", line 77 in worker_process
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/worker.py", line 112 in main
  File "/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1/Lib/test/libregrtest/worker.py", line 116 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main

Total duration: 23 min 32 sec
Total tests: run=36,420 failures=16 skipped=1,361
Total test files: run=414/423 failed=17 skipped=27 resource_denied=9
Result: FAILURE
make: *** [Makefile:888: profile-run-stamp] Error 2
 * ERROR: dev-lang/python-3.13.0_beta1_p1::gentoo failed (compile phase):
 *   emake failed
 *
 * If you need support, post the output of `emerge --info '=dev-lang/python-3.13.0_beta1_p1::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/python-3.13.0_beta1_p1::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1'
 * S: '/var/tmp/portage/dev-lang/python-3.13.0_beta1_p1/work/Python-3.13.0b1'







Comment 1


Conrad Kostecki






          2024-05-12 16:28:35 UTC
        

            Comment hidden (obsolete)
          

Created attachment 892825 [details]
build.log




Comment 2


Conrad Kostecki






          2024-05-12 16:29:01 UTC
        

Created attachment 892826 [details]
emerge.log

emerge --info




Comment 3


Conrad Kostecki






          2024-05-12 16:29:29 UTC
        

Created attachment 892827 [details]
build.log




Comment 4


Conrad Kostecki






          2024-09-18 20:54:55 UTC
        

Closing, as I am not able to reproduce anymore?









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

