Title: 351166 – dev-python/pygtksourceview-2.10.1 fails to configure if dev-lang/python-2.7 is selected as default
URL: https://bugs.gentoo.org/show_bug.cgi?id=351166

Go to: 
		Gentoo Home
Documentation
Forums
Lists
Bugs
Planet
Store
Wiki
Get Gentoo!





Gentoo's Bugzilla – Bug 351166
dev-python/pygtksourceview-2.10.1 fails to configure if dev-lang/python-2.7 is selected as default
Last modified: 2011-01-09 15:15:12 UTC node [vulture]


Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]













Bug 351166 
      - dev-python/pygtksourceview-2.10.1 fails to configure if dev-lang/python-2.7 is selected as default


Summary:
dev-python/pygtksourceview-2.10.1 fails to configure if dev-lang/python-2.7 i...
        









Status:
    

RESOLVED
          WORKSFORME
      






Alias:


        None
    





Product:

Gentoo Linux




Classification:

Unclassified




Component:

New packages

  (show other bugs)



Hardware:

All
        Linux
      







Importance:
      
High
       normal
      


Assignee:

Gentoo Linux bug wranglers








URL:







Whiteboard:




Keywords:








Depends on:







Blocks:









 





      Reported:
    
2011-01-08 23:36 UTC by Alex Buell





      Modified:
    
2011-01-09 15:15 UTC
      (History)
    




          CC List:
        

0 
          users
        








See Also:






Package list:







Runtime testing required:

---























      Attachments
    



Add an attachment
        (proposed patch, testcase, etc.)
    








Note
              You need to
              log in
              before you can comment on or make changes to this bug.
            

















Description


Alex Buell





          2011-01-08 23:36:48 UTC
        

dev-python/pygtksourceview during configuration fails to find codegen if dev-lang/python-2.7 is set as default. Perhaps time to find a newer version?




Comment 1


Rafał Mużyło





          2011-01-08 23:44:54 UTC
        

Perhaps it's time to run python-updater ?




Comment 2


Alex Buell





          2011-01-08 23:53:34 UTC
        

(In reply to comment #1)
> Perhaps it's time to run python-updater ?

That will be the next thing to do, once I've got all the packages built on this unstable x86 box (for testing purposes)




Comment 3


Alex Buell





          2011-01-09 10:26:38 UTC
        

python-updater resolved the problem, consider this closed.









Format For Printing
 - XML
 - Clone This Bug
 - Clone In The Same 
                        Product
 - Top of page 







Home
| New–[Ex]
| Browse
| Search
| Privacy Policy

| 





[?]
| Reports

| 
Requests

| 
Help


| 
New Account


| 
Log In





[x]



| 
Forgot Password

Login:




[x]

